# Generated by Django 2.1 on 2018-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('word_text', models.CharField(max_length=140)),
                ('date_time', models.DateTimeField(verbose_name='投稿日')),
            ],
        ),
    ]
